### ISSUE TITLE
NPE on master

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#318]
Just caught this beast here:
```
08-31 13:06:00.089 3878-3878/com.kamron.pogoiv E/MainActivity: Error thrown in grabScreen() - acquireLatestImage()
08-31 13:06:00.124 3878-3878/com.kamron.pogoiv E/ScreenGrabber: java.lang.NullPointerException: Attempt to invoke virtual method 'android.media.Image android.media.ImageReader.acquireLatestImage()' on a null object reference
                                                                    at com.kamron.pogoiv.ScreenGrabber.grabScreen(ScreenGrabber.java:66)
                                                                    at com.kamron.pogoiv.Pokefly.scanPokemonScreen(Pokefly.java:385)
                                                                    at com.kamron.pogoiv.Pokefly.access$000(Pokefly.java:76)
                                                                    at com.kamron.pogoiv.Pokefly$1$1.run(Pokefly.java:371)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

Around that moment, I stopped the service, swiped away the app, and cleared the cache. Not sure which is relevant, but "race condition with the timer when stopping the service" might be it.

**Comment by sarav** [comment]
Hmmm... that's why I do the timer.cancel() first in the onDestroy() for Pokefly. So, it shouldn't happen. Unless timer.cancel() doesn't wait for a currently running timer to finish before returning.

**Comment by sarav** [comment]
Poor Java API. From the timer.cancel() doc:

> Terminates this timer, discarding any currently scheduled tasks. Does not interfere with a currently executing task (if it exists). Once a timer has been terminated, its execution thread terminates gracefully, and no more tasks may be scheduled on it.

They should have had something like timer.cancel_and_finish() or something if they didn't want cancel to wait for the currently running one to finish.

**Comment by sarav** [comment]
I think we should move to one of the Android mechanics for periodic work instead of using java.util.Timer. Let's fix this after #296

**Comment by Blaisorblade** [comment]
IIUC this is just a stacktrace on shutdown, hence it shouldn't impact stability too much. Fine with me.

**Comment by sarav** [comment]
This could happen when someone just hits stop too. But, it should be hard to hit.

**Comment by Blaisorblade** [comment]
As long as we don't deadlock that's hopefully fine as well. But I should check.

**Comment by Blaisorblade** [comment]
This is by far the most common stack trace in Crashlytics for 3.1.0:
http://crashes.to/s/cf49a698164

`grabScreen` ends up returning null. In master that was already handled correctly for screen recording mode, and I fixed it for screenshot mode in fc008d7b286236dc7522e491f2dcb5e1088fc7c8. The crash we had up to 3.1.0 was tracked in http://crashes.to/s/95ed8d63bd0.

**Comment by Blaisorblade** [comment]
Should be closed by @sarav's change to not use a Timer.

**Comment by sarav** [comment]
Heh... Deleting code is one way to close the issue I guess. :)
