### ISSUE TITLE
2.1 Crash, 2.0 Disappear, 1.3 fine

### ISSUE THREAD

**Issue by joduya123** [farkam135/GoIV#82]
So I tried out the 2.1 and the app kept crashing or disappearing on my OnePlus one.  on 2.0 the IV button kept disappearing (but never crashed).  I never had these problems with version 1.30

**Comment by aidanhs** [comment]
Yeah it's breaking a fair bit for me too. Only particular pokemon though. Process is
 - go to page of 'bad' pokemon, e.g. a particular drowzee
 - press IV icon
 - IV icon vanishes
 - go back to goiv and press 'stop'
 - 'goiv has stopped', i.e. crash

**Comment by nahojjjen** [comment]
I'm guessing the "IV disappearing" is caused by this crash:


> Non-fatal Exception: java.lang.NumberFormatException: Invalid int: ""
       at java.lang.Integer.invalidInt(Integer.java:138)
       at java.lang.Integer.parseInt(Integer.java:358)
       at java.lang.Integer.parseInt(Integer.java:334)
       at com.kamron.pogoiv.MainActivity.scanPokemon(Unknown Source)
       at com.kamron.pogoiv.MainActivity.takeScreenshot(Unknown Source)
       at com.kamron.pogoiv.MainActivity.access$2000(Unknown Source)
       at com.kamron.pogoiv.MainActivity$4.onReceive(Unknown Source)
       at android.support.v4.content.LocalBroadcastManager.getInstance(Unknown Source)
       at android.support.v4.content.LocalBroadcastManager.getInstance(Unknown Source)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5264)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)



Thats a crashreport from crashlytics, I'll try to make a fix for it & include it in my refactor pull #75

**Comment by nahojjjen** [comment]
Okay, its solved on my phone now on #75
