### ISSUE TITLE
Instant crash at startup in offline release build

### ISSUE THREAD

**Issue by ghost** [farkam135/GoIV#913]
I just built 5.0.2 from source in offline mode. The release apk crashes instantly on my Android 5.1.1 device, but the debug apk starts normally. Same behavior with a 5.0.1 build. Here's a logcat of the 5.0.2 release crash:

    I/ActivityManager( 2170): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.swanberg.pogoiv.nointernet/com.kamron.pogoiv.activities.MainActivity bnds=[430,614][570,798] (has extras)} from uid 10018 on display 0
    V/WindowManager( 2170): addAppToken: AppWindowToken{382ae019 token=Token{312a0360 ActivityRecord{23841b63 u0 com.swanberg.pogoiv.nointernet/com.kamron.pogoiv.activities.MainActivity t6337}}} to stack=1 task=6337 at 0
    V/WindowManager( 2170): Adding window Window{658de78 u0 Starting com.swanberg.pogoiv.nointernet} at 9 of 14 (after Window{2443be85 u0 com.android.settings/com.android.settings.applications.InstalledAppDetails})
    I/ActivityManager( 2170): Start proc 5913:com.swanberg.pogoiv.nointernet/u0a107 for activity com.swanberg.pogoiv.nointernet/com.kamron.pogoiv.activities.MainActivity
    V/WindowManager( 2170): rotationForOrientationLw(orient=1, last=0); user=0 
    V/ActivityManager( 2170): Display changed displayId=0
    D/AndroidRuntime( 5913): Shutting down VM
    --------- beginning of crash
    E/AndroidRuntime( 5913): FATAL EXCEPTION: main
    E/AndroidRuntime( 5913): Process: com.swanberg.pogoiv.nointernet, PID: 5913
    E/AndroidRuntime( 5913): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.swanberg.pogoiv.nointernet/com.kamron.pogoiv.activities.MainActivity}: android.view.InflateException: Binary XML file line #33: Error inflating class ImageView
    E/AndroidRuntime( 5913):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
    E/AndroidRuntime( 5913):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
    E/AndroidRuntime( 5913):        at android.app.ActivityThread.access$900(ActivityThread.java:154)
    E/AndroidRuntime( 5913):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
    E/AndroidRuntime( 5913):        at android.os.Handler.dispatchMessage(Handler.java:102)
    E/AndroidRuntime( 5913):        at android.os.Looper.loop(Looper.java:135)
    E/AndroidRuntime( 5913):        at android.app.ActivityThread.main(ActivityThread.java:5294)
    E/AndroidRuntime( 5913):        at java.lang.reflect.Method.invoke(Native Method)
    E/AndroidRuntime( 5913):        at java.lang.reflect.Method.invoke(Method.java:372)
    E/AndroidRuntime( 5913):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    E/AndroidRuntime( 5913):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
    E/AndroidRuntime( 5913): Caused by: android.view.InflateException: Binary XML file line #33: Error inflating class ImageView
    E/AndroidRuntime( 5913):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
    E/AndroidRuntime( 5913):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
    E/AndroidRuntime( 5913):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
    E/AndroidRuntime( 5913):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
    E/AndroidRuntime( 5913):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
    E/AndroidRuntime( 5913):        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
    E/AndroidRuntime( 5913):        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
    E/AndroidRuntime( 5913):        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
    E/AndroidRuntime( 5913):        at android.support.v7.app.ae.b(AppCompatDelegateImplV9.java:287)
    E/AndroidRuntime( 5913):        at android.support.v7.app.o.setContentView(AppCompatActivity.java:139)
    E/AndroidRuntime( 5913):        at com.kamron.pogoiv.activities.MainActivity.onCreate(MainActivity.java:157)
    E/AndroidRuntime( 5913):        at android.app.Activity.performCreate(Activity.java:5990)
    E/AndroidRuntime( 5913):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
    E/AndroidRuntime( 5913):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
    E/AndroidRuntime( 5913):        ... 10 more
    E/AndroidRuntime( 5913): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.au.d()' on a null object reference
    E/AndroidRuntime( 5913):        at android.support.v7.widget.av.setImageDrawable(AppCompatImageView.java:101)
    E/AndroidRuntime( 5913):        at android.widget.ImageView.<init>(ImageView.java:148)
    E/AndroidRuntime( 5913):        at android.widget.ImageView.<init>(ImageView.java:135)
    E/AndroidRuntime( 5913):        at android.support.v7.widget.av.<init>(AppCompatImageView.java:71)
    E/AndroidRuntime( 5913):        at android.support.v7.widget.av.<init>(AppCompatImageView.java:67)
    E/AndroidRuntime( 5913):        at android.support.v7.app.at.a(AppCompatViewInflater.java:106)
    E/AndroidRuntime( 5913):        at android.support.v7.app.ae.onCreateView(AppCompatDelegateImplV9.java:10016)
    E/AndroidRuntime( 5913):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
    E/AndroidRuntime( 5913):        ... 23 more
    W/ActivityManager( 2170):   Force finishing activity 1 com.swanberg.pogoiv.nointernet/com.kamron.pogoiv.activities.MainActivity
    I/OpenGLRenderer( 2170): Initialized EGL, version 1.4
    W/ActivityManager( 2170): Activity pause timeout for ActivityRecord{23841b63 u0 com.swanberg.pogoiv.nointernet/com.kamron.pogoiv.activities.MainActivity t6337 f}
    V/WindowManager( 2170): rotationForOrientationLw(orient=5, last=0); user=0

**Comment by thearaks** [comment]
Hi @mewio!
I've just tried to install the offline release apk available on GitHub and it didn't crash.
Then I tried to recompile offline release from sources and, again, it all went smooth.
Could it be some kind of issue with your development setup?
Have you tried to clean the project and rebuild it from scratch?

**Comment by mewio** [comment]
I did clean the project and rebuild it from scratch, but the new build also crashed. The apk from github doesn't crash.

Okay, so something is different between my build and the official one. But what? And, why doesn't the debug build crash as well? [Here's the build log.](https://gist.github.com/mewio/d509428dc08e929364bbdbc800ddbc1f)

**Comment by nahojjjen** [comment]
It's missing the fabric API key, but that shouldnt affect the offline version...

**Comment by gaurav-m** [comment]
Hi
I am facing the same issue with my own application.
Signed APK is crashing, and with the same exception as mentioned above.
Debug (non-obfuscated) build run fine.

This suddenly started happening. I launched a signed apk only about a week ago.

Change log since last successful signed build:

- Updated firebase login ui
- Added following in proguard, as I started facing methodnot found exception Facebook's SmartLoginUi.
`-keep enum com.facebook.** {
    **[] $VALUES;
    public *;
}`

Now I am getting 
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.av.d()' on a null object reference
        at android.support.v7.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:101)
        at android.widget.ImageView.<init>(ImageView.java:190)`

Dont know whats up with this.

I am writing here because no where online i found this issue mentioned.

**Comment by gaurav-m** [comment]
FYI
I downgraded gradle plugin from 3.1.2 back to 3.1.1
Its working now.

**Comment by mewio** [comment]
Thanks, @gaurav-m. I was going to try your suggestion, but the latest release worked for me without that downgrade.
